# Generated by Django 3.1.7 on 2021-10-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=2000)),
                ('rank', models.BigIntegerField()),
                ('ip_check', models.IntegerField()),
                ('valid', models.IntegerField()),
                ('active_duration', models.IntegerField()),
                ('urlLEn', models.IntegerField()),
                ('at_check', models.IntegerField()),
                ('redirect_check', models.IntegerField()),
                ('have_dash', models.IntegerField()),
                ('domain_len', models.IntegerField()),
                ('nu_of_subdomain', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
